version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/static:/app/app/static

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:80"
